FROM mcr.microsoft.com/dotnet/sdk:8.0 AS development
WORKDIR /app

COPY . .

RUN dotnet restore "Rest/Rest.csproj"
RUN dotnet build "Rest/Rest.csproj" -c Release --no-restore

EXPOSE 80
ENTRYPOINT ["dotnet", "run", "--project", "Rest/Rest.csproj", "--no-restore", "--urls", "http://0.0.0.0:80"]