FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY . .
RUN dotnet restore "Rest/Rest.csproj"
RUN dotnet build "Rest/Rest.csproj" -c Release
EXPOSE 80
ENTRYPOINT ["dotnet", "Rest/Rest.dll"]